// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/2.0/mlflow/experiments/get": {
            "get": {
                "description": "Get metadata for an experiment",
                "produces": [
                    "application/json"
                ],
                "summary": "Get metadata for an experiment",
                "operationId": "get-experiment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the associated experiment",
                        "name": "experiment_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/experiment.Experiment"
                        }
                    }
                }
            }
        },
        "/2.0/mlflow/runs/get": {
            "get": {
                "description": "Get metadata for a run",
                "produces": [
                    "application/json"
                ],
                "summary": "Get metadata for a run",
                "operationId": "get-run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the associated run",
                        "name": "run_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/run.Run"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "experiment.Experiment": {
            "type": "object",
            "properties": {
                "artifact_location": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "integer"
                },
                "experiment_id": {
                    "type": "string"
                },
                "last_update_time": {
                    "type": "integer"
                },
                "lifecycle_stage": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/experiment.ExperimentTag"
                    }
                }
            }
        },
        "experiment.ExperimentTag": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "run.DatasetInput": {
            "type": "object",
            "properties": {
                "dataset_id": {
                    "type": "string"
                },
                "dataset_name": {
                    "type": "string"
                }
            }
        },
        "run.Metric": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "run.Param": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "run.Run": {
            "type": "object",
            "properties": {
                "artifact_uri": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/run.RunData"
                },
                "end_time": {
                    "type": "integer"
                },
                "experiment_id": {
                    "type": "string"
                },
                "info": {
                    "$ref": "#/definitions/run.RunInfo"
                },
                "inputs": {
                    "$ref": "#/definitions/run.RunInputs"
                },
                "lifecycle_stage": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "run_name": {
                    "type": "string"
                },
                "run_uuid": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "run.RunData": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/run.Metric"
                    }
                },
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/run.Param"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/run.RunTag"
                    }
                }
            }
        },
        "run.RunInfo": {
            "type": "object",
            "properties": {
                "artifact_uri": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "experiment_id": {
                    "type": "string"
                },
                "lifecycle_stage": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "run_name": {
                    "type": "string"
                },
                "run_uuid": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "run.RunInputs": {
            "type": "object",
            "properties": {
                "dataset_inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/run.DatasetInput"
                    }
                }
            }
        },
        "run.RunTag": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "MLFlow Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Simple wrapper around MLFlow API for Krateo Operator Generator (KOG)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
