openapi: 3.0.1
info:
  title: MLFlow Plugin API for Krateo Operator Generator (KOG)
  description: Simple wrapper around MLFlow API for Krateo Operator Generator (KOG)
  termsOfService: http://swagger.io/terms/
  contact:
    name: Krateo Support
    url: https://krateo.io
    email: contact@krateoplatformops.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
servers:
- url: http://localhost:8080/
paths:
  /2.0/mlflow/experiments/get:
    get:
      summary: Get metadata for an experiment
      description: Get metadata for an experiment
      operationId: get-experiment
      parameters:
      - name: experiment_id
        in: query
        description: ID of the associated experiment
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/experiment.Experiment'
  /2.0/mlflow/runs/get:
    get:
      summary: Get metadata for a run
      description: Get metadata for a run
      operationId: get-run
      parameters:
      - name: run_id
        in: query
        description: ID of the associated run
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/run.Run'
components:
  schemas:
    experiment.Experiment:
      type: object
      properties:
        artifact_location:
          type: string
        creation_time:
          type: integer
        experiment_id:
          type: string
        last_update_time:
          type: integer
        lifecycle_stage:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/experiment.ExperimentTag'
    experiment.ExperimentTag:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    run.DatasetInput:
      type: object
      properties:
        dataset_id:
          type: string
        dataset_name:
          type: string
    run.Metric:
      type: object
      properties:
        key:
          type: string
        timestamp:
          type: integer
        value:
          type: number
    run.Param:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    run.Run:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/run.RunData'
        info:
          $ref: '#/components/schemas/run.RunInfo'
        inputs:
          $ref: '#/components/schemas/run.RunInputs'
    run.RunData:
      type: object
      properties:
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/run.Metric'
        params:
          type: array
          items:
            $ref: '#/components/schemas/run.Param'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/run.RunTag'
    run.RunInfo:
      type: object
      properties:
        artifact_uri:
          type: string
        end_time:
          type: integer
        experiment_id:
          type: string
        lifecycle_stage:
          type: string
        run_id:
          type: string
        run_name:
          type: string
        run_uuid:
          type: string
        start_time:
          type: integer
        status:
          type: string
        user_id:
          type: string
    run.RunInputs:
      type: object
      properties:
        dataset_inputs:
          type: array
          items:
            $ref: '#/components/schemas/run.DatasetInput'
    run.RunTag:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
x-original-swagger-version: "2.0"
